### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by shasihui** [chenjiandongx/HupuLive#2]
C:\Users\Alby>hupu -h
Traceback (most recent call last):
  File "C:\Python36\Scripts\hupu-script.py", line 11, in <module>
    load_entry_point('HupuLive==1.3', 'console_scripts', 'hupu')()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python36\lib\site-packages\hupulive-1.3-py3.6.egg\hupu.py", line 30, in <module>
ModuleNotFoundError: No module named 'docopt'

**Comment by chenjiandongx** [comment]
没安装 docopt 库，使用``` pip install docopt``` 安装。然后再重新安装 HupuLive 试一试

**Comment by shasihui** [comment]
Traceback (most recent call last):
  File "C:\Python36\Scripts\hupu-script.py", line 11, in <module>
    load_entry_point('HupuLive==1.3', 'console_scripts', 'hupu')()
  File "C:\Python36\lib\site-packages\hupulive-1.3-py3.6.egg\hupu.py", line 197, in cli
  File "C:\Python36\lib\site-packages\hupulive-1.3-py3.6.egg\hupu.py", line 46, in __init__
  File "C:\Python36\lib\site-packages\hupulive-1.3-py3.6.egg\hupu.py", line 78, in get_gamelist
  File "C:\Python36\lib\site-packages\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by shasihui** [comment]
parser 这个库安装的时候
Collecting parser
  Could not find a version that satisfies the requirement parser (from versions: )
No matching distribution found for parser

**Comment by chenjiandongx** [comment]
应该指的是 lxml 库，用 ```pip install lxml``` 安装，我来更新一下 setup 文件

**Comment by shasihui** [comment]
OK 可以了  python小白第一次玩 哈哈

**Comment by chenjiandongx** [comment]
嗯 那我关闭这个 issue 了
